1. Daily Orders
Question

Find daily total orders.

SELECT
    DATE(order_time) AS order_date,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY DATE(order_time)
ORDER BY order_date;
------------------------------------------



2. Total Revenue by City

SELECT
    city_id,
    SUM(order_amount) AS revenue
FROM orders
GROUP BY city_id;
------------------------------------------


3. Active Couriers
Count distinct couriers who completed orders

  SELECT
    COUNT(DISTINCT courier_id) AS active_couriers
FROM orders
WHERE status = 'completed';
------------------------------------------

4. Average Delivery Time
SELECT
    AVG(cdt_minutes) AS avg_cdt
FROM orders;
--------------------------------------------


-- LEVEL 2 — JOINS + CASE WHEN

-- These are VERY common.

5. Orders with City Name

Tables:

orders
cities

SELECT
    o.order_id,
    c.city_name,
    o.order_amount
FROM orders o
JOIN cities c
    ON o.city_id = c.city_id;
--------------------------------------------

6. Acceptance Rate
Formula

accepted orders / assigned orders

SELECT
    ROUND(
        100.0 * SUM(
            CASE WHEN accepted = 1 THEN 1 ELSE 0 END
        ) / COUNT(*),
        2
    ) AS acceptance_rate
FROM courier_dispatch;
----------------------------------------------

7. Peak vs Non-Peak Orders

  
SELECT
    CASE
        WHEN HOUR(order_time) BETWEEN 18 AND 22
        THEN 'Peak'
        ELSE 'Non-Peak'
    END AS order_period,
    COUNT(*) AS total_orders
FROM orders
GROUP BY 1;
-------------------------------------------

--   LEVEL 3 — INTERMEDIATE ANALYTICS

--  This is where Bolt-level interviews begin.

8. Top 3 Cities by Revenue

-- Using window functions.

WITH city_revenue AS (

SELECT
    city_id,
    SUM(order_amount) AS revenue
FROM orders
GROUP BY city_id

)

SELECT *
FROM (

    SELECT
        *,
        RANK() OVER (
            ORDER BY revenue DESC
        ) AS rn
    FROM city_revenue

       ) x
WHERE rn <= 3;

---------------------------------------

-- Difference Between Ranking Functions
ROW_NUMBER()

-- Unique numbering.

ROW_NUMBER() OVER (
    PARTITION BY city_id
    ORDER BY revenue DESC
)

-- Example:
1,2,3,4

RANK()

-- Skips numbers after ties.

-- Example:
1,1,3,4

DENSE_RANK()

-- No skipped numbers.

Example:
1,1,2,3

---------------------------------------------

-- LEVEL 4 — WINDOW FUNCTIONS

-- VERY important for this role.

-- 9. Day-over-Day CDT Change

  
  WITH daily_cdt AS (

                     SELECT
                         DATE(order_time) AS dt,
                         AVG(cdt_minutes) AS avg_cdt
                     FROM orders
                     GROUP BY 1

                     )

SELECT
    dt,
    avg_cdt,
    LAG(avg_cdt) OVER ( ORDER BY dt
                      ) AS prev_day_cdt,
    
    avg_cdt - LAG(avg_cdt) OVER (ORDER BY dt
                      ) AS cdt_change
FROM daily_cdt;
----------------------------------------------

-- 10. Rolling 7-Day Average

SELECT
    DATE(order_time) AS dt, 
    AVG(cdt_minutes) OVER (
                            ORDER BY DATE(order_time)
                            ROWS BETWEEN 6 PRECEDING
                            AND CURRENT ROW
    ) AS rolling_7d_avg
FROM orders;
--------------------------------

Q1

Find total completed orders per day.

Table: orders

Columns:

order_id
order_time
status

Condition:

only completed orders

Expected output:

order_date
total_completed_orders

SELECT 
  DATE(order_time) AS order_date ,
  COUNT(order_id) AS total_completed_orders
FROM orders
WHERE status = 'completed'
GROUP BY DATE(order_time)
ORDER BY order_date
----------------------------------------

Q2

Find total revenue generated by each city.

Table: orders

Columns:

order_id
city_id
order_amount

Expected output:

city_id
total_revenue

SELECT 
  city_id,
  SUM(order_amount) AS total_revenue
FROM orders
GROUP BY city_id
ORDER BY city_id DESC 
---------------------------------------




  
Q3

Find the number of distinct active couriers.

Table: orders

Columns:

courier_id
status

Condition:

only couriers with at least 1 completed order

Expected output:

active_couriers

SELECT 
  DISTINCT(courier_id) AS active_couriers
FROM orders
WHERE status = 'completed'


SELECT
    COUNT(DISTINCT courier_id) AS active_couriers
FROM orders
WHERE status = 'completed'
--------------------------------------------------

Q4

Find average CDT by city.

Table: orders

Columns:

city_id
cdt_minutes

Expected output:

city_id
avg_cdt
INTERMEDIATE LEVEL

SELECT 
  city_id,
  AVG(cdt_minutes) AS avg_cdt
FROM orders
GROUP BY city_id
ORDER BY AVG(cdt_minutes) DESC
-------------------------------------------------------



  
Q5

Find top 5 cities with highest order volume.

Table: orders

Columns:

city_id
order_id

Expected output:

city_id
total_orders

SELECT 
    city_id,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY city_id
ORDER BY total_orders DESC
LIMIT 5
----------------------------------------

  
Q6

Calculate courier acceptance rate.

Table: courier_dispatch

Columns:

dispatch_id
courier_id
accepted (1 or 0)

Expected output:

acceptance_rate_percentage

SELECT
    ROUND( 100.0 * SUM(
                    CASE
                        WHEN accepted = 1 THEN 1
                    ELSE 0
                  END
                       ) / COUNT(*),
        2 ) AS acceptance_rate_percentage
FROM courier_dispatch;


-------------------------------------
Q7

Classify orders into:

Peak Hours (18:00–22:00)
Non-Peak Hours

Table: orders

Columns:

order_id
order_time

Expected output:

order_period
total_orders


SELECT
CASE 
   WHEN order_time BETWEEN 18:00 AND 22:00 THEN Peak_Hours
 ELSE Non_Peak_Hours
END, 
COUNT(order_id)
FROM orders
GROUP BY 1

SELECT
    CASE
        WHEN HOUR(order_time) BETWEEN 18 AND 22
        THEN 'Peak Hours'
        ELSE 'Non-Peak Hours'
    END AS order_period,
    
    COUNT(order_id) AS total_orders

FROM orders
GROUP BY 1;










  
Q8

Find the 2nd highest revenue-generating city.

Table: orders

Columns:

city_id
order_amount

Expected output:

city_id
total_revenue
WINDOW FUNCTION LEVEL
Q9

Find day-over-day change in average CDT.

Table: orders

Columns:

order_time
cdt_minutes

Expected output:

order_date
avg_cdt
previous_day_cdt
cdt_change
Q10

Find rolling 7-day average CDT.

Table: orders

Columns:

order_time
cdt_minutes

Expected output:

order_date
rolling_7d_avg_cdt
Q11

For each city, rank couriers based on total completed orders.

Table: orders

Columns:

city_id
courier_id
order_id
status

Expected output:

city_id
courier_id
total_completed_orders
rank
HARD LEVEL
Q12

Find cities where:

average CDT is above company average
AND
acceptance rate is below 80%

Tables:

orders
city_id
cdt_minutes
courier_dispatch
city_id
accepted

Expected output:

city_id
avg_cdt
acceptance_rate
Q13

Find merchants with highest average wait time.

Table: orders

Columns:

merchant_id
courier_arrival_time
food_ready_time

Expected output:

merchant_id
avg_wait_time
Q14

Find consecutive days where acceptance rate declined for each city.

Table: courier_dispatch

Columns:

city_id
dispatch_time
accepted

Expected output:

city_id
date
acceptance_rate
declining_flag
Q15

Break down total CDT into:

dispatch_time
wait_time
delivery_time

Table: orders

Columns:

city_id
dispatch_time
wait_time
delivery_time

Expected output:

city_id
avg_dispatch_time
avg_wait_time
avg_delivery_time
total_avg_cdt
VERY HARD / MANAGER LEVEL
Q16

Identify the top 10% worst-performing orders by CDT.

Table: orders

Columns:

order_id
city_id
cdt_minutes

Expected output:

order_id
city_id
cdt_minutes
percentile_rank
Q17

A city’s CDT increased by 20% week-over-week.

Write SQL to compare:

dispatch time
wait time
delivery time

between current week and previous week.

Table: orders

Columns:

city_id
order_time
dispatch_time
wait_time
delivery_time

Expected output:

city_id
metric_name
previous_week_avg
current_week_avg
percentage_change
Q18

Find couriers whose acceptance rate is consistently below city average.

Tables:

courier_dispatch
courier_id
city_id
accepted

Expected output:

courier_id
city_id
courier_acceptance_rate
city_avg_acceptance_rate
Q19

Find the busiest hour for each city.

Table: orders

Columns:

city_id
order_time
order_id

Expected output:

city_id
busiest_hour
total_orders
Q20

Calculate cancellation rate by:

city
hour of day

Table: orders

Columns:

city_id
order_time
status

Condition:

cancelled orders / total orders

Expected output:

city_id
hour_of_day
cancellation_rate

















